// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QQbot.DataAccess.Contexts;

namespace QQbot.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200827001253_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QQbot.DataAccess.Entities.AdminAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectMatchId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("SubjectMatchId");

                    b.HasIndex("SubjectPlayerId");

                    b.ToTable("AdminHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminId = 1,
                            SubjectPlayerId = 1,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 914, DateTimeKind.Utc).AddTicks(9254)
                        },
                        new
                        {
                            Id = 2,
                            AdminId = 1,
                            SubjectPlayerId = 2,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(1815)
                        },
                        new
                        {
                            Id = 3,
                            AdminId = 1,
                            SubjectPlayerId = 3,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(1905)
                        },
                        new
                        {
                            Id = 4,
                            AdminId = 1,
                            SubjectPlayerId = 4,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(1985)
                        },
                        new
                        {
                            Id = 5,
                            AdminId = 1,
                            SubjectPlayerId = 5,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2029)
                        },
                        new
                        {
                            Id = 6,
                            AdminId = 1,
                            SubjectPlayerId = 6,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2069)
                        },
                        new
                        {
                            Id = 7,
                            AdminId = 1,
                            SubjectPlayerId = 7,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2107)
                        },
                        new
                        {
                            Id = 8,
                            AdminId = 1,
                            SubjectPlayerId = 8,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2146)
                        },
                        new
                        {
                            Id = 9,
                            AdminId = 1,
                            SubjectPlayerId = 9,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2186)
                        },
                        new
                        {
                            Id = 10,
                            AdminId = 1,
                            SubjectPlayerId = 10,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2225)
                        },
                        new
                        {
                            Id = 11,
                            AdminId = 1,
                            SubjectPlayerId = 11,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2263)
                        },
                        new
                        {
                            Id = 12,
                            AdminId = 1,
                            SubjectPlayerId = 12,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2301)
                        },
                        new
                        {
                            Id = 13,
                            AdminId = 1,
                            SubjectPlayerId = 13,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2339)
                        },
                        new
                        {
                            Id = 14,
                            AdminId = 1,
                            SubjectPlayerId = 14,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2377)
                        },
                        new
                        {
                            Id = 15,
                            AdminId = 1,
                            SubjectPlayerId = 15,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2415)
                        },
                        new
                        {
                            Id = 16,
                            AdminId = 1,
                            SubjectPlayerId = 16,
                            Type = 2,
                            When = new DateTime(2020, 8, 27, 0, 12, 52, 915, DateTimeKind.Utc).AddTicks(2480)
                        });
                });

            modelBuilder.Entity("QQbot.DataAccess.Entities.LobbyPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Joined")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Lobby");
                });

            modelBuilder.Entity("QQbot.DataAccess.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LosingTeamId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Submitted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LosingTeamId");

                    b.HasIndex("WinningTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("QQbot.DataAccess.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Discord")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Submitted")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Discord")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discord = 240413827718578177L,
                            Name = "Slam",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(4388)
                        },
                        new
                        {
                            Id = 2,
                            Discord = 175325337196953600L,
                            Name = "Yoko",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5392)
                        },
                        new
                        {
                            Id = 3,
                            Discord = 287275232236929026L,
                            Name = "Candyboy",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5415)
                        },
                        new
                        {
                            Id = 4,
                            Discord = 232147476008796161L,
                            Name = "Godly",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5417)
                        },
                        new
                        {
                            Id = 5,
                            Discord = 416266623847235584L,
                            Name = "Santana",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5418)
                        },
                        new
                        {
                            Id = 6,
                            Discord = 208987498368598016L,
                            Name = "Purif",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5422)
                        },
                        new
                        {
                            Id = 7,
                            Discord = 361620009815900170L,
                            Name = "Chrona",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5423)
                        },
                        new
                        {
                            Id = 8,
                            Discord = 382998762533945344L,
                            Name = "Lisek",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5425)
                        },
                        new
                        {
                            Id = 9,
                            Discord = 277194459576532992L,
                            Name = "Oln",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5426)
                        },
                        new
                        {
                            Id = 10,
                            Discord = 288009866080157697L,
                            Name = "Rainy",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5429)
                        },
                        new
                        {
                            Id = 11,
                            Discord = 465126942656561152L,
                            Name = "Butters",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5430)
                        },
                        new
                        {
                            Id = 12,
                            Discord = 241149128216674305L,
                            Name = "Takida",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5432)
                        },
                        new
                        {
                            Id = 13,
                            Discord = 99492885015048192L,
                            Name = "Jo",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5433)
                        },
                        new
                        {
                            Id = 14,
                            Discord = 221445321530540032L,
                            Name = "Bounty",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5435)
                        },
                        new
                        {
                            Id = 15,
                            Discord = 430796233783640066L,
                            Name = "Cracks",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5436)
                        },
                        new
                        {
                            Id = 16,
                            Discord = 242126086983516160L,
                            Name = "Jonas",
                            Rating = 1000,
                            Status = 2,
                            Submitted = new DateTime(2020, 8, 27, 0, 12, 52, 913, DateTimeKind.Utc).AddTicks(5438)
                        });
                });

            modelBuilder.Entity("QQbot.DataAccess.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("QQbot.DataAccess.Entities.TeamPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("QQbot.DataAccess.Entities.AdminAction", b =>
                {
                    b.HasOne("QQbot.DataAccess.Entities.Player", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QQbot.DataAccess.Entities.Match", "SubjectMatch")
                        .WithMany()
                        .HasForeignKey("SubjectMatchId");

                    b.HasOne("QQbot.DataAccess.Entities.Player", "SubjectPlayer")
                        .WithMany()
                        .HasForeignKey("SubjectPlayerId");
                });

            modelBuilder.Entity("QQbot.DataAccess.Entities.LobbyPlayer", b =>
                {
                    b.HasOne("QQbot.DataAccess.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QQbot.DataAccess.Entities.Match", b =>
                {
                    b.HasOne("QQbot.DataAccess.Entities.Team", "LosingTeam")
                        .WithMany()
                        .HasForeignKey("LosingTeamId");

                    b.HasOne("QQbot.DataAccess.Entities.Team", "WinningTeam")
                        .WithMany()
                        .HasForeignKey("WinningTeamId");
                });

            modelBuilder.Entity("QQbot.DataAccess.Entities.TeamPlayer", b =>
                {
                    b.HasOne("QQbot.DataAccess.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QQbot.DataAccess.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
