// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QQbot.Api.Contexts;

namespace QQbot.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200218110516_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QQbot.Api.Entities.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Joined")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Lobby");
                });

            modelBuilder.Entity("QQbot.Api.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LosingTeamId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LosingTeamId");

                    b.HasIndex("WinningTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("QQbot.Api.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DiscordId")
                        .HasColumnType("bigint");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("PlaysBack")
                        .HasColumnType("bit");

                    b.Property<bool>("PlaysFront")
                        .HasColumnType("bit");

                    b.Property<bool>("PlaysMid")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscordId = 240413827718578177L,
                            Losses = 0,
                            Name = "Slam",
                            PlaysBack = true,
                            PlaysFront = true,
                            PlaysMid = false,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            DiscordId = 175325337196953600L,
                            Losses = 0,
                            Name = "Yoko",
                            PlaysBack = false,
                            PlaysFront = true,
                            PlaysMid = true,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            DiscordId = 287275232236929026L,
                            Losses = 0,
                            Name = "Candy",
                            PlaysBack = false,
                            PlaysFront = true,
                            PlaysMid = true,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            DiscordId = 232147476008796161L,
                            Losses = 0,
                            Name = "Godly",
                            PlaysBack = false,
                            PlaysFront = false,
                            PlaysMid = true,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            DiscordId = 416266623847235584L,
                            Losses = 0,
                            Name = "Santana",
                            PlaysBack = true,
                            PlaysFront = false,
                            PlaysMid = false,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            DiscordId = 208987498368598016L,
                            Losses = 0,
                            Name = "Purif",
                            PlaysBack = true,
                            PlaysFront = false,
                            PlaysMid = true,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            DiscordId = 361620009815900170L,
                            Losses = 0,
                            Name = "Chrona",
                            PlaysBack = false,
                            PlaysFront = true,
                            PlaysMid = true,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            DiscordId = 382998762533945344L,
                            Losses = 0,
                            Name = "Lisek",
                            PlaysBack = true,
                            PlaysFront = false,
                            PlaysMid = true,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            DiscordId = 277194459576532992L,
                            Losses = 0,
                            Name = "Oln",
                            PlaysBack = true,
                            PlaysFront = false,
                            PlaysMid = false,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 10,
                            DiscordId = 288009866080157697L,
                            Losses = 0,
                            Name = "Rainy",
                            PlaysBack = true,
                            PlaysFront = false,
                            PlaysMid = false,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 11,
                            DiscordId = 465126942656561152L,
                            Losses = 0,
                            Name = "Butters",
                            PlaysBack = false,
                            PlaysFront = true,
                            PlaysMid = true,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 12,
                            DiscordId = 241149128216674305L,
                            Losses = 0,
                            Name = "Takida",
                            PlaysBack = false,
                            PlaysFront = true,
                            PlaysMid = false,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 13,
                            DiscordId = 99492885015048192L,
                            Losses = 0,
                            Name = "Jo",
                            PlaysBack = false,
                            PlaysFront = false,
                            PlaysMid = true,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 14,
                            DiscordId = 221445321530540032L,
                            Losses = 0,
                            Name = "Bounty",
                            PlaysBack = false,
                            PlaysFront = true,
                            PlaysMid = true,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 15,
                            DiscordId = 430796233783640066L,
                            Losses = 0,
                            Name = "Cracks",
                            PlaysBack = false,
                            PlaysFront = true,
                            PlaysMid = false,
                            Rating = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 16,
                            DiscordId = 242126086983516160L,
                            Losses = 0,
                            Name = "Jonas",
                            PlaysBack = true,
                            PlaysFront = true,
                            PlaysMid = true,
                            Rating = 0,
                            Wins = 0
                        });
                });

            modelBuilder.Entity("QQbot.Api.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("QQbot.Api.Entities.TeamPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RatingAfter")
                        .HasColumnType("int");

                    b.Property<int>("RatingBefore")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("QQbot.Api.Entities.Lobby", b =>
                {
                    b.HasOne("QQbot.Api.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("QQbot.Api.Entities.Match", b =>
                {
                    b.HasOne("QQbot.Api.Entities.Team", "LosingTeam")
                        .WithMany()
                        .HasForeignKey("LosingTeamId");

                    b.HasOne("QQbot.Api.Entities.Team", "WinningTeam")
                        .WithMany()
                        .HasForeignKey("WinningTeamId");
                });

            modelBuilder.Entity("QQbot.Api.Entities.TeamPlayer", b =>
                {
                    b.HasOne("QQbot.Api.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("QQbot.Api.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
